### ISSUE TITLE
This project is dead?

### ISSUE THREAD

**Issue by blackPantherOS** [jkamsk/mdbsqlgui#1]
Hi, The connection does not work now. You drop this good project? A easy interface like this good idea for new users...

**Comment by jkamsk** [comment]
Hi, I have not stopped the project yet, but the truth is that I do not have much time. I have not even known that anyone uses it (except me :)).

So, from now on, I will try to bring this project into a more complete form.
Can you please give me more details about non-working connections?
Operating system (with version), Qt version, MariaDB version etc ... the more information the better

**Comment by blackPantherOS** [comment]
Sure, I would like to first know what is state the project... so:
MariaDb-10.1.18
qt5-database-plugin-mysql-5.6.2
Started in konsole, I don't get any error or debug msg.
I thinking that this is a connector bug, but other application working fine what use qt5-database-plugin, like owncloud-client

![image](https://user-images.githubusercontent.com/12883566/27729209-3887f948-5d85-11e7-9f79-e6125a45084f.png)

**Comment by jkamsk** [comment]
Ok, State of the project is initial only. Basic features are described in readme file.
I Have currently preparing a version 0.2. Changes in version 0.2 will be:
A) More verbose with connection login errors: Now isn't posible show and debug your 'connection error' problem (used versions of components not helped me)

Note: Table structure editor. (MENUs: Edit Table, New Table) Is not very useful, In version 0.3 will be a more complex with foreign key part and improved editting

please be patient

**Comment by jkamsk** [comment]
Please, try version 0.2 and post error message here.

**Comment by blackPantherOS** [comment]
0.2 and new build is working fine (closable)

I sent a pull requiest with format string fix.
This project marked as supported application in blackPanther OS.
![image](https://user-images.githubusercontent.com/12883566/27859363-d3390d32-6178-11e7-9510-546f873a776d.png)
